### ISSUE TITLE
Error on "return (int) NULL;"

### ISSUE THREAD

**Issue by liar666** [pavlin-policar/openTSNE#161]
I'm trying to install openTSNE (0.4.4) under OpenBSD (6.8) with pip (21.0.1) Python (3.8.6)

##### Expected behaviour

Should compile & install flawlessly

##### Actual behaviour
Compilation stops on 

```
  cc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -g -fPIC -O2 -pipe -g -O2 -pipe -g -fPIC -I/home/guigui/Python/DataScience/include -I/home/guigui/Python/DataScience/Library/include -I/home/guigui/Python/DataScience/lib/python3.8/site-packages/numpy/core/include -I/home/guigui/Python/DataScience/include -I/usr/local/include/python3.8 -c openTSNE/dependencies/annoy/annoymodule.cc -o build/temp.openbsd-6.8-amd64-3.8/openTSNE/dependencies/annoy/annoymodule.o -std=c++14 -DANNOYLIB_MULTITHREADED_BUILD -O3
  openTSNE/dependencies/annoy/annoymodule.cc:180:12: error: cast from pointer to smaller type 'int' loses information
      return (int) NULL;
             ^~~~~~~~~~
  1 error generated.
  error: command 'cc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for openTSNE
```

Such a cast is indeed a bad practice. Code should be changed. Also, in the meantime, less strict compilation options should be selected so that the code compiles and package installs on all target platforms.

##### Steps to reproduce the behavior

`python3 - m pip install openTSNE`

**Comment by pavlin-policar** [comment]
This is a very strange error indeed, and, unfortunately, one we can't fix. All the C++ code is generated by cython, so there is actually no C++ code maintained in this repository. Concretely, the Python extensions are written in the Cython language e.g. [openTSNE/_tsne.pyx](https://github.com/pavlin-policar/openTSNE/blob/master/openTSNE/_tsne.pyx), which automatically get translated into C++, producing [openTSNE/_tsne.cpp](https://github.com/pavlin-policar/openTSNE/blob/master/openTSNE/_tsne.cpp). When we introduce changes into these .pyx modules, we run it through cython and a new .cpp file is generated.

If you're installing openTSNE using pip, and it's downloading the source distribution i.e. non-precompiled binary, then your platform probably isn't supported. OpenBSD 6.8. is relatively new, so there are a few options:
- cython doesn't support this platform,
- pip doesn't know how to properly resolve the wheel, or
- most likely, the last release of openTSNE was built at a time when this platform wasn't yet supported, and the precompiled binaries are unsupported.

It's also strange that it's trying to install openTSNE v0.4.4, while the latest version is 0.5.1.

I think you might be able to fix the problem by installing cython (`pip install cython`), then running the installation process again. If this doesn't work, try cloning the latest release and installing directly from there using `python setup.py install`. You can then delete the cloned directory.

Also, please update your issue to include information about your compiler. This may help users experiencing the same problem in the future.

**Comment by pavlin-policar** [comment]
Closing to inactivity. Feel free to reopen if you need any additional help.
